import type { Metadata } from "next";
import { StyledRoot } from "./@theme/styledRoot";
import StyledComponentsRegistry from "./@core/lib/registry";

import { Container } from "react-bootstrap";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Suspense } from "react";
import LoadingSystem from "./@core/components/ui/Loading/Loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        <Container fluid>
          <AppRouterCacheProvider>
            <StyledComponentsRegistry>
              <StyledRoot>
                <Suspense fallback={<LoadingSystem />}>
                  {children}
                </Suspense>
              </StyledRoot>
            </StyledComponentsRegistry>
          </AppRouterCacheProvider>
        </Container>
      </body>
    </html>
  );
}
