import type { Metadata } from "next";
import "./globals.css";
import { StyledRoot } from "./@theme/styledRoot";
import StyledComponentsRegistry from "./@core/lib/registry";

import { Container } from "react-bootstrap";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
      </head>
      <body className={`antialiased`}>
        <Container fluid>
          <AppRouterCacheProvider>
            <StyledComponentsRegistry>
              <StyledRoot>{children}</StyledRoot>
            </StyledComponentsRegistry>
          </AppRouterCacheProvider>
        </Container>
      </body>
    </html>
  );
}
